# Generated by Django 2.0.7 on 2018-09-13 19:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_REST', '0002_auto_20180913_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('fecha', models.DateField(default=datetime.date.today, primary_key=True, serialize=False)),
                ('asistencia', models.CharField(max_length=100)),
                ('grupoxestudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_REST.GrupoXEstudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('fecha', models.DateField(default=datetime.date.today, primary_key=True, serialize=False)),
                ('acumulador', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='estudiantexcategoria',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='estudiantexcategoria',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='estudiantexsubcategoria',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='estudiantexsubcategoria',
            name='subcategoria',
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='profesorxgrupo',
            name='jornada',
        ),
        migrations.AddField(
            model_name='categoria',
            name='subcategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API_REST.Categoria'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ano',
            field=models.SmallIntegerField(default=2018),
        ),
        migrations.AddField(
            model_name='grupo',
            name='consecutivo',
            field=models.CharField(default='NA', max_length=3),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='icono',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='EstudianteXCategoria',
        ),
        migrations.DeleteModel(
            name='EstudianteXSubcategoria',
        ),
        migrations.DeleteModel(
            name='Subcategoria',
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='Categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_REST.Categoria'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='grupoxestudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_REST.GrupoXEstudiante'),
        ),
    ]
