# Generated by Django 2.0.7 on 2018-09-13 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_REST', '0003_auto_20180913_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seguimiento',
            old_name='Categoria',
            new_name='categoria',
        ),
    ]
