# Generated by Django 2.0.7 on 2018-10-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_REST', '0003_categoria_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='tipo_documento',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
