# Generated by Django 2.0.7 on 2018-09-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_REST', '0004_auto_20180913_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='icono',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='consecutivo',
            field=models.CharField(default='NA', max_length=4),
        ),
    ]
