# Generated by Django 2.0.7 on 2018-09-14 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_REST', '0006_auto_20180914_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='grupoxestudiante',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='grupoxestudiante',
        ),
        migrations.DeleteModel(
            name='Asistencia',
        ),
        migrations.DeleteModel(
            name='Seguimiento',
        ),
    ]
