# Generated by Django 2.0.7 on 2018-09-14 20:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_REST', '0007_auto_20180914_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('asistencia', models.CharField(max_length=100)),
                ('grupoxestudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_REST.GrupoXEstudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('acumulador', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_REST.Categoria')),
                ('grupoxestudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_REST.GrupoXEstudiante')),
            ],
        ),
    ]
