# Generated by Django 2.0.7 on 2018-09-16 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_REST', '0008_asistencia_seguimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='asistencia',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_REST.Categoria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='sexo_biologico',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='sexo_biologico',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profesorxgrupo',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_REST.Profesor'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API_REST.Categoria'),
        ),
    ]
