# Generated by Django 2.0.7 on 2018-10-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_REST', '0012_auto_20181003_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoxestudiante',
            name='columna',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='grupoxestudiante',
            name='fila',
            field=models.IntegerField(default=-1),
        ),
    ]
