# Generated by Django 2.0.7 on 2018-10-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_REST', '0014_auto_20181023_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='habilitada',
            field=models.BooleanField(default=True),
        ),
    ]
